version: '2'
networks:
  frontend-web:
    external: true
  backend:
    driver: bridge
services:
  database:
    image: postgres:10
    volumes:
      - /data/bases/ecobasa.org/data:/var/lib/postgresql/data
    #  - ./django.sql:/docker-entrypoint-initdb.d/django.sql
    env_file:
      - ./postgres.env
    networks:
      - backend
    logging:
      driver: none
  django:
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
    #  - ./src/:/opt/services/ecobasa/
      - ./media:/opt/services/ecobasa/media
      - ./locale/django.de.mo:/opt/services/ecobasa/ecobasa/locale/de/LC_MESSAGES/django.mo
      - ./locale/django.es.mo:/opt/services/ecobasa/ecobasa/locale/es/LC_MESSAGES/django.mo
      - ./static-collected:/opt/services/ecobasa/static-collected
      - ./whoosh_index:/opt/services/ecobasa/whoosh_index
      - ./settings.py:/opt/services/ecobasa/ecobasa/settings.py
    depends_on:
      - database
    networks:
      - backend
    #logging:
    #  driver: none

  nginx:
    image: nginx
    expose: ["80"]
    env_file:
      - ./frontend.env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static-collected:/opt/services/ecobasa/static-collected
      - ./media:/opt/services/ecobasa/media
    depends_on:
      - django
    networks:
      - backend
      - frontend-web
    logging:
      driver: none
